services:
  web:
    container_name: webBackendChat
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c
      "python manage.py migrate && python manage.py test && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 7999:8000
    env_file:
      - ./djangoChat/.env
    depends_on:
      - redis
      - postgres
  postgres:
    container_name: postgresChat
    image: postgres:latest
    restart: on-failure
    env_file:
      - ./djangoChat/.env
  redis:
    container_name: redisChat
    image: redis:alpine
    restart: on-failure
    command: redis-server
